import { test, expect } from '@playwright/test';

test.describe('Document Compliance Platform E2E', () => {
  test('User can navigate dashboard and access rules page', async ({ page }) => {
    // 1. Visit Dashboard
    await page.goto('/');
    await expect(page).toHaveTitle(/Document Compliance Checker/);
    
    // 2. Verify UI elements are present
    await expect(page.getByText('Upload Document')).toBeVisible();
    await expect(page.getByText('Rules Active')).toBeVisible();

    // 3. Navigate to Rules Page
    await page.getByRole('link', { name: 'Rules' }).click();
    await expect(page.getByText('Create Rule Template')).toBeVisible();
  });

  test('User can create a rule template', async ({ page }) => {
    // Since we are running E2E, the backend API should ideally be mocked, 
    // but in a full stack test we interact directly.
    await page.goto('/rules');
    
    // Switch to JSON editor for faster rule creation in tests
    await page.getByRole('tab', { name: 'JSON Editor' }).click();
    
    const ruleInput = page.locator('textarea');
    await ruleInput.fill(JSON.stringify({
      name: "E2E Test Rule",
      description: "Generated by Playwright",
      margins: { top: 1, bottom: 1, left: 1, right: 1 },
      font: { family: "Arial", size: 12 }
    }));

    // Submit rule
    // We expect the native alert to trigger
    page.on('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Import JSON Rule' }).click();
    
    // Verify it succeeded (in a real app we'd verify the toast or redirection, here we just ensure no crash)
  });
});
